// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.18083
//    <NameSpace></NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net30</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><AutomaticProperties>True</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Generic;


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Actor
{

    private string firstnameField;

    private string lastnameField;

    private bool principalActorField;

    private bool principalActorFieldSpecified;

    private string nationalityField;

    public string firstname { get; set; }

    public string lastname { get; set; }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool PrincipalActor { get; set; }

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrincipalActorSpecified { get; set; }


    public Actor()
    {
        this.nationalityField = "US";
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("US")]
    public string nationality
    {
        get
        {
            return this.nationalityField;
        }
        set
        {
            this.nationalityField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class DvdCollection
{

    private List<dvd> dvdsField;

    public DvdCollection()
    {
        this.dvdsField = new List<dvd>();
    }

    [System.Xml.Serialization.XmlElementAttribute("Dvds")]
    public List<dvd> Dvds
    {
        get
        {
            return this.dvdsField;
        }
        set
        {
            this.dvdsField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
public partial class dvd
{

    private string yearField;

    private System.Nullable<System.DateTime> publishField;

    private string titleField;

    private Styles styleField;

    private List<Actor> actorField;

    private int publishYearField;

    private dvdCover coverField;

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Year { get; set; }

    [System.Xml.Serialization.XmlElementAttribute(DataType = "date", IsNullable = true)]
    public System.Nullable<System.DateTime> Publish { get; set; }

    public int PublishYear { get; set; }

    public dvdCover Cover { get; set; }


    public dvd()
    {
        this.coverField = new dvdCover();
        this.actorField = new List<Actor>();
        this.titleField = "DefaultTitle";
        this.styleField = Styles.Action;
    }

    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    public Styles Style
    {
        get
        {
            return this.styleField;
        }
        set
        {
            this.styleField = value;
        }
    }

    [System.Xml.Serialization.XmlElementAttribute("Actor")]
    public List<Actor> Actor
    {
        get
        {
            return this.actorField;
        }
        set
        {
            this.actorField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
public enum Styles
{

    /// <remarks/>
    Action,

    /// <remarks/>
    Fiction,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class dvdCover
{

    private string systemeField;

    private string valueField;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Systeme { get; set; }

    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value { get; set; }

}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Actors
{

    private List<Actor> actorField;

    public Actors()
    {
        this.actorField = new List<Actor>();
    }

    [System.Xml.Serialization.XmlElementAttribute("Actor")]
    public List<Actor> Actor
    {
        get
        {
            return this.actorField;
        }
        set
        {
            this.actorField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
public partial class mycttype
{

    private double valueField;

    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value { get; set; }

}
