// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.3.0.16585
//    <NameSpace>Xsd2Code.TestUnit</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Xsd2Code.TestUnit {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class testOptionalElements {
        
        private testOptionalElementsOptionalInt optionalIntField;
        
        private testOptionalElementsOptionalString optionalStringField;
        
        private List<testOptionalElementsOptionRepeatedInt> optionRepeatedIntField;
        
        public testOptionalElements() {
            this.optionRepeatedIntField = new List<testOptionalElementsOptionRepeatedInt>();
            this.optionalStringField = new testOptionalElementsOptionalString();
            this.optionalIntField = new testOptionalElementsOptionalInt();
        }
        
        public testOptionalElementsOptionalInt optionalInt {
            get {
                return this.optionalIntField;
            }
            set {
                this.optionalIntField = value;
            }
        }
        
        public testOptionalElementsOptionalString optionalString {
            get {
                return this.optionalStringField;
            }
            set {
                this.optionalStringField = value;
            }
        }
        
        public List<testOptionalElementsOptionRepeatedInt> optionRepeatedInt {
            get {
                return this.optionRepeatedIntField;
            }
            set {
                this.optionRepeatedIntField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class testOptionalElementsOptionalInt {
        
        private int valueField;
        
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class testOptionalElementsOptionalString {
        
        private string valueField;
        
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class testOptionalElementsOptionRepeatedInt {
        
        private int valueField;
        
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
